add russian language
P3D-Legacy/P3D-Legacy pull request #19
Opened 2018-06-13 23:14 UTC by Virg29

2018-06-14 16:23 UTC, Aragas requested changes
Needs fixing

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +delete_menu_delete_confirm,Вы уверены что хотите удалить сохранение
Вы уверены, что хотите...

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +pause_menu_confirmation,Вы уверенны что хотите выйти?Несохраненный прогресс будет потерян.
Вы уверенны, что...

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +new_game_oak_1,Привет! * Добро пожаловать в мир ~ Покемонов! * Меня зовут Оак. ~ Люди называют меня ~ Проффесор Покемон * Этот мир населен ~ существами, которые мы называем
Профессор

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +new_game_oak_2,Покемонами.*Люди и покемоны живут бок о бок и помогают друг другу.Некоторые люди предпочитают играть с покемонами другие участвуют с ними в сражениях*Однако нам еще не все известно о п
~ отсутствуют

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +new_game_oak_known_name_2,!*Хм я уверена что слышала это имя.
Хм,
Хм...
Я уверен

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +new_game_oak_same_name_1,Да мы тески*У меня такое же~
...такое же имя

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +option_screen_animations_in_battle_description,Показывать анимацию во время битвы или нет
...или нет можно убрать

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +apricorn_screen_ready,Я доделал покеболы, можешь взглянуть:
Встречаются покеболлы и покеболы. 
Используй покебол с одной л

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +daycare_screen_pokemon_choose_header,Заложить покемона
Заложить не лучший термин. Отдать?
На твое усмотрение

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +Places_Route 1,Route 1
Ты роуты переводишь как маршруты. Стоит перевести это тоже

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +donation_screen_donators,Донаты
Донаторы/жертвователи

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +battle_attack_paralyzed, парализован!~онт не может двинуться!
Очепятка

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +badge_Plain,Гладкий
Plain тут в контексте "простой", если я не ошибаюсь

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +Places_New Bark Town,New Bark Town
Возможно, стоит перевести названия.
Что-то в стиле "(Городок?) Нью Барк"
Town городок
City город

2018-06-14 16:23 UTC, Aragas commented on P3D/Content/Localization/Tokens_ru.dat
> +Places_Oak's lab,Лабаратория Оаки
Оака?

2018-06-15 22:10 UTC, Virg29 commented on P3D/Content/Localization/Tokens_ru.dat
> +Places_Oak's lab,Лабаратория Оаки
По спрайту предполагал, что это женщина)

2018-06-15 22:18 UTC, closed without merging