Fix old namespace checks on crash log generator and a nice fix for turkish users :)
P3D-Legacy/P3D-Legacy pull request #69
Opened 2021-06-15 13:59 UTC by jianmingyong

2021-06-16 06:29 UTC, Aragas requested changes

2021-06-16 06:29 UTC, Aragas commented on P3D/Core/GameController.vb
> +        If CultureInfo.CurrentCulture.EnglishName = "Turkish" Then
Why do we change only the Turkish language parsing? Are other languages fine?
Couldn't this be achieved by using an inveriant parsing?
The specific issue is not stated, but I assume this is something about us showing or parsing in wrong format?
Please specify!

2021-06-16 06:31 UTC, Aragas commented
Everything else looks fine btw

2021-09-23 02:35 UTC, jianmingyong commented
Removed the other fix for now. This can go standalone for now.

2021-09-24 06:26 UTC, merged